# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "wolverineav"
languageCode = "en-us"
baseURL = "https://wolverineav.github.io"
copyright = "Â© {year}"

# Add your Disqus shortname here.
disqusShortname = "wolverineav"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-172766817-1"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2 Jan 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/wolverineav"
  github = "https://github.com/wolverineav"
  linkedin = "https://www.linkedin.com/in/adityavaja/"
  # email = "mailto:<your email>"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["Twitter", "GitHub", "LinkedIn"]

[params.colors]
    fancy = "#F1C40F"

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

